"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { BusinessContext } from "@/types"
import { AIInsightsEngine, AIInsight, SuggestedAction } from "@/lib/ai-insights"
import { AIInsightsGeminiEngine } from "@/lib/ai-insights-gemini"
import {
  Sparkles,
  AlertTriangle,
  CheckCircle,
  Info,
  Target,
  TrendingUp,
  ChevronRight,
  Plus,
  X,
  Zap,
  Loader2
} from "lucide-react"
import { cn } from "@/lib/utils"

interface AIInsightsProps {
  businessContext: BusinessContext
  onAddAction?: (action: Omit<SuggestedAction, "id" | "autoGenerated">) => void
  aiInsights?: AIInsight[]
  suggestedActions?: SuggestedAction[]
  isLoading?: boolean
}

export function AIInsights({
  businessContext,
  onAddAction,
  aiInsights = [],
  suggestedActions: suggestedActionsFromProps = [],
  isLoading = false
}: AIInsightsProps) {
  const [dismissedInsights, setDismissedInsights] = useState<Set<string>>(new Set())
  const [dismissedActions, setDismissedActions] = useState<Set<string>>(new Set())

  // Use props directly (no internal generation)
  const insights = aiInsights
  const suggestedActions = suggestedActionsFromProps

  const getInsightIcon = (type: AIInsight["type"]) => {
    switch (type) {
      case "warning":
        return <AlertTriangle className="h-5 w-5 text-orange-600" />
      case "success":
        return <CheckCircle className="h-5 w-5 text-green-600" />
      case "opportunity":
        return <Target className="h-5 w-5 text-blue-600" />
      default:
        return <Info className="h-5 w-5 text-purple-600" />
    }
  }

  const getInsightBgColor = (type: AIInsight["type"]) => {
    switch (type) {
      case "warning":
        return "bg-orange-50 dark:bg-orange-950/20 border-orange-200 dark:border-orange-900"
      case "success":
        return "bg-green-50 dark:bg-green-950/20 border-green-200 dark:border-green-900"
      case "opportunity":
        return "bg-blue-50 dark:bg-blue-950/20 border-blue-200 dark:border-blue-900"
      default:
        return "bg-purple-50 dark:bg-purple-950/20 border-purple-200 dark:border-purple-900"
    }
  }

  const getPriorityBadge = (priority: string) => {
    const colors = {
      high: "bg-red-100 text-red-800 border-red-300 dark:bg-red-900 dark:text-red-200",
      medium: "bg-orange-100 text-orange-800 border-orange-300 dark:bg-orange-900 dark:text-orange-200",
      low: "bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-900 dark:text-blue-200"
    }
    const labels = { high: "Urgent", medium: "Moyen", low: "Faible" }
    return (
      <Badge className={colors[priority as keyof typeof colors]} variant="outline">
        {labels[priority as keyof typeof labels]}
      </Badge>
    )
  }

  const handleDismissInsight = (id: string) => {
    setDismissedInsights(prev => new Set(prev).add(id))
  }

  const handleDismissAction = (id: string) => {
    setDismissedActions(prev => new Set(prev).add(id))
  }

  const handleAcceptAction = (action: SuggestedAction) => {
    if (onAddAction) {
      onAddAction({
        title: action.title,
        description: action.description,
        priority: action.priority,
        dueDate: action.dueDate,
        relatedTo: action.relatedTo,
        completed: false
      })
      handleDismissAction(action.id)
    }
  }

  const visibleInsights = insights.filter(i => !dismissedInsights.has(i.id))
  const visibleActions = suggestedActions.filter(a => !dismissedActions.has(a.id))

  return (
    <>
      {/* Colonne 1 : Insights IA */}
      <div>
        {isLoading ? (
          <Card className="shadow-xl border-2 border-purple-200/50 dark:border-purple-800/50 bg-gradient-to-br from-purple-50/80 to-pink-50/80 dark:from-purple-950/50 dark:to-pink-950/50 backdrop-blur-sm">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 shadow-lg">
                    <Loader2 className="h-5 w-5 text-white animate-spin" />
                  </div>
                  <div>
                    <CardTitle className="text-lg">Génération insights...</CardTitle>
                    <CardDescription>Analyse en cours</CardDescription>
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="p-4 rounded-xl border-2 bg-white/50 dark:bg-slate-900/50 animate-pulse">
                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 bg-purple-200 dark:bg-purple-800 rounded-full shrink-0" />
                      <div className="flex-1 space-y-2">
                        <div className="h-4 bg-purple-200 dark:bg-purple-800 rounded w-3/4" />
                        <div className="h-3 bg-purple-100 dark:bg-purple-900 rounded w-full" />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        ) : visibleInsights.length > 0 ? (
        <Card className="shadow-xl border-2 border-purple-200/50 dark:border-purple-800/50 bg-gradient-to-br from-purple-50/80 to-pink-50/80 dark:from-purple-950/50 dark:to-pink-950/50 backdrop-blur-sm">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 shadow-lg">
                  {isLoading ? (
                    <Loader2 className="h-5 w-5 text-white animate-spin" />
                  ) : (
                    <Sparkles className="h-5 w-5 text-white" />
                  )}
                </div>
                <div>
                  <CardTitle className="text-lg flex items-center gap-2">
                    IA Insights du jour
                  </CardTitle>
                  <CardDescription>
                    {isLoading ? "Analyse en cours..." : "Analyse intelligente de votre activité"}
                  </CardDescription>
                </div>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            {visibleInsights.map((insight, index) => (
              <div
                key={insight.id}
                className={cn(
                  "p-4 rounded-xl border-2 transition-all duration-300",
                  "animate-in slide-in-from-left-3",
                  getInsightBgColor(insight.type)
                )}
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="flex items-start gap-3">
                  <div className="shrink-0 mt-0.5">
                    {getInsightIcon(insight.type)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-2 mb-2">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-2xl">{insight.icon}</span>
                        <h4 className="font-bold text-sm">{insight.title}</h4>
                        {insight.priority === "high" && getPriorityBadge(insight.priority)}
                      </div>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6 shrink-0"
                        onClick={() => handleDismissInsight(insight.id)}
                      >
                        <X className="h-3 w-3" />
                      </Button>
                    </div>
                    <p className="text-sm text-muted-foreground">{insight.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
        ) : (
          <Card className="shadow-xl border-2 border-purple-200/50 dark:border-purple-800/50">
            <CardContent className="py-12 text-center text-muted-foreground">
              <Sparkles className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p>Aucun insight disponible pour le moment</p>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Colonne 2 : Actions suggérées */}
      <div>
        {isLoading ? (
          <Card className="shadow-xl border-2 border-blue-200/50 dark:border-blue-800/50 bg-gradient-to-br from-blue-50/80 to-cyan-50/80 dark:from-blue-950/50 dark:to-cyan-950/50 backdrop-blur-sm">
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-xl bg-gradient-to-br from-blue-600 to-cyan-600 shadow-lg">
                  <Loader2 className="h-5 w-5 text-white animate-spin" />
                </div>
                <div>
                  <CardTitle className="text-lg">Génération actions...</CardTitle>
                  <CardDescription>Recommandations en cours</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {[1, 2].map((i) => (
                  <div key={i} className="p-4 rounded-xl border-2 bg-white/50 dark:bg-slate-900/50 animate-pulse">
                    <div className="flex items-start gap-3">
                      <div className="flex-1 space-y-2">
                        <div className="h-4 bg-blue-200 dark:bg-blue-800 rounded w-2/3" />
                        <div className="h-3 bg-blue-100 dark:bg-blue-900 rounded w-full" />
                        <div className="h-8 bg-blue-100 dark:bg-blue-900 rounded w-1/3" />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        ) : visibleActions.length > 0 ? (
        <Card className="shadow-xl border-2 border-blue-200/50 dark:border-blue-800/50 bg-gradient-to-br from-blue-50/80 to-cyan-50/80 dark:from-blue-950/50 dark:to-cyan-950/50 backdrop-blur-sm">
          <CardHeader className="pb-3">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-gradient-to-br from-blue-600 to-cyan-600 shadow-lg">
                <TrendingUp className="h-5 w-5 text-white" />
              </div>
              <div>
                <CardTitle className="text-lg">Actions suggérées par l'IA</CardTitle>
                <CardDescription>Recommandations personnalisées pour optimiser vos ventes</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            {visibleActions.map((action, index) => (
              <div
                key={action.id}
                className={cn(
                  "p-4 rounded-xl border-2 transition-all duration-300",
                  "bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700",
                  "hover:border-blue-400 dark:hover:border-blue-600 hover:shadow-lg",
                  "animate-in slide-in-from-right-3"
                )}
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="flex items-start justify-between gap-3 mb-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      <h4 className="font-bold text-sm">{action.title}</h4>
                      {getPriorityBadge(action.priority)}
                    </div>
                    <p className="text-sm text-muted-foreground mb-2">{action.description}</p>
                    {action.relatedTo && (
                      <Badge variant="secondary" className="text-xs">
                        📎 {action.relatedTo.name}
                      </Badge>
                    )}
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    onClick={() => handleAcceptAction(action)}
                    className="flex-1 gap-1 bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700"
                  >
                    <Plus className="h-3 w-3" />
                    Accepter
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleDismissAction(action.id)}
                    className="gap-1"
                  >
                    Plus tard
                    <ChevronRight className="h-3 w-3" />
                  </Button>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
        ) : (
          <Card className="shadow-xl border-2 border-blue-200/50 dark:border-blue-800/50">
            <CardContent className="py-12 text-center text-muted-foreground">
              <TrendingUp className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p>Aucune action suggérée pour le moment</p>
            </CardContent>
          </Card>
        )}
      </div>
    </>
  )
}
