import { BusinessContext, Deal, Lead, Activity, ActionItem, BusinessMetrics } from "@/types"

export const demoMetrics: BusinessMetrics = {
  revenue: 245000,
  revenueGrowth: 12.5,
  leads: 1234,
  leadsGrowth: 8.2,
  conversionRate: 24.5,
  conversionRateChange: -2.4,
  pipelineValue: 850000,
  pipelineGrowth: 15.8,
  averageDealSize: 45000,
  salesCycle: 45,
}

export const demoDeals: Deal[] = [
  {
    id: "1",
    company: "TechCorp Solutions",
    value: 250000,
    stage: "Négociation",
    probability: 75,
    contact: "Marie Dubois",
    lastActivity: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    nextStep: "Présentation finale au comité de direction",
    tags: ["Enterprise", "SaaS"],
  },
  {
    id: "2",
    company: "Innovation Partners",
    value: 180000,
    stage: "Proposition",
    probability: 60,
    contact: "Pierre Martin",
    lastActivity: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    nextStep: "Envoyer la proposition commerciale détaillée",
    tags: ["Consulting"],
  },
  {
    id: "3",
    company: "Digital Ventures",
    value: 95000,
    stage: "Qualification",
    probability: 40,
    contact: "Sophie Laurent",
    lastActivity: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    nextStep: "Qualifier le budget et l'échéancier",
    tags: ["Digital", "Marketing"],
  },
  {
    id: "4",
    company: "Startup Accelerator",
    value: 75000,
    stage: "Prospection",
    probability: 25,
    contact: "Jean Dupont",
    lastActivity: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    nextStep: "Premier appel de découverte",
    tags: ["Startup"],
  },
]

export const demoLeads: Lead[] = [
  {
    id: "1",
    company: "FutureTech Inc",
    contact: "Alice Bernard",
    email: "alice.bernard@futuretech.fr",
    phone: "+33 6 12 34 56 78",
    source: "LinkedIn",
    score: 85,
    status: "Qualifié",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    lastContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    notes: "Très intéressé par notre solution SaaS. Budget confirmé pour Q1.",
  },
  {
    id: "2",
    company: "Smart Industries",
    contact: "Marc Rousseau",
    email: "m.rousseau@smartind.fr",
    source: "Salon professionnel",
    score: 72,
    status: "Contacté",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    lastContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    notes: "Rencontré au salon. Souhaite une démo de notre plateforme.",
  },
  {
    id: "3",
    company: "GreenEnergy Solutions",
    contact: "Claire Moreau",
    email: "claire.m@greenenergy.fr",
    phone: "+33 6 98 76 54 32",
    source: "Site web",
    score: 65,
    status: "Nouveau",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    notes: "Demande d'information via formulaire web.",
  },
]

export const demoActivities: Activity[] = [
  {
    id: "1",
    type: "won",
    description: "Deal signé avec Acme Corp",
    company: "Acme Corp",
    value: 125000,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "2",
    type: "demo",
    description: "Démo produit pour TechCorp Solutions",
    company: "TechCorp Solutions",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "3",
    type: "call",
    description: "Appel de suivi avec Innovation Partners",
    company: "Innovation Partners",
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "4",
    type: "proposal",
    description: "Proposition envoyée à Digital Ventures",
    company: "Digital Ventures",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "5",
    type: "meeting",
    description: "RDV qualification avec FutureTech Inc",
    company: "FutureTech Inc",
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
]

export const demoActionItems: ActionItem[] = [
  {
    id: "1",
    title: "Préparer présentation finale TechCorp",
    description: "Créer le deck de présentation pour le comité de direction avec focus ROI",
    priority: "high",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    completed: false,
    relatedTo: {
      type: "deal",
      id: "1",
      name: "TechCorp Solutions",
    },
  },
  {
    id: "2",
    title: "Envoyer proposition Innovation Partners",
    description: "Finaliser et envoyer la proposition commerciale détaillée",
    priority: "high",
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    completed: false,
    relatedTo: {
      type: "deal",
      id: "2",
      name: "Innovation Partners",
    },
  },
  {
    id: "3",
    title: "Relancer FutureTech Inc",
    description: "Appeler Alice Bernard pour planifier la démo produit",
    priority: "medium",
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    completed: false,
    relatedTo: {
      type: "lead",
      id: "1",
      name: "FutureTech Inc",
    },
  },
  {
    id: "4",
    title: "Analyse concurrentielle",
    description: "Mettre à jour le tableau comparatif vs concurrents pour les pitchs",
    priority: "medium",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    completed: false,
  },
  {
    id: "5",
    title: "Révision forecast Q1",
    description: "Revoir les prévisions de ventes pour le trimestre en cours",
    priority: "low",
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    completed: false,
  },
]

export const demoBusinessContext: BusinessContext = {
  metrics: demoMetrics,
  topDeals: demoDeals,
  recentActivities: demoActivities,
  actionItems: demoActionItems,
  hotLeads: demoLeads.filter((l) => l.score >= 70),
}
